server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    # Disable caching for index.html
    location ~* \.html$ {
        expires -1;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    }

    # Serve the latest JS file if an old cached one is requested
    location ~* ^/assets/index-.*\.js$ {
        try_files $uri /assets/index-BcUcd2o9.js;
    }

    # SPA routing fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
