services:
  backend:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - redis
      - db  # Добавили зависимость от базы
    ports:
      - "8000:8000"

  redis:
    env_file: .env
    image: redis:7.2.2-alpine3.18
    restart: always
    command:
      - redis-server
      - --appendonly yes
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - ${REDIS_PORT}:6379

  # --- ДОБАВЬТЕ ЭТОТ БЛОК ---
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./diary
    restart: always
    ports:
      - "3000:80"

volumes:
  redis-data:
  postgres-data: # Добавили том для данных БД
