"""fix_1

Revision ID: 0af81bff4115
Revises: 0c3fd95e3024
Create Date: 2024-06-12 19:11:51.626664

"""
from typing import Sequence, Union

import inspect
import sqlalchemy as sa
from alembic import op

# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = '0af81bff4115'
down_revision: Union[str, None] = '0c3fd95e3024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('uuid', sa.Text(), nullable=True))
    op.alter_column('payments', 'category_id',
                    existing_type=sa.BIGINT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'category_id',
                    existing_type=sa.BIGINT(),
                    nullable=False)
    op.drop_column('payments', 'uuid')
    op.drop_column('payments', 'url')
    # ### end Alembic commands ###
