"""cascade

Revision ID: 0c3fd95e3024
Revises: b4fcfec6e20d
Create Date: 2024-06-11 21:39:39.687502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect


# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = '0c3fd95e3024'
down_revision: Union[str, None] = 'b4fcfec6e20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)

# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'answers' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'answers', ['id'])
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'categories' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'categories', ['id'])
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'payments' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'payments', ['id'])
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'progresses' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'progresses', ['id'])
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'questions' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'questions', ['id'])
    op.drop_constraint('questions_test_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_id'], ['id'], ondelete='CASCADE')
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'results' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'results', ['id'])
    conn = op.get_bind()

    res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'tests' AND constraint_type = 'UNIQUE'"))

    if not res.fetchall():

        op.create_unique_constraint(None, 'tests', ['id'])
    op.drop_constraint('tests_category_id_fkey', 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key('tests_category_id_fkey', 'tests', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'tests', type_='unique')
    op.drop_constraint(None, 'results', type_='unique')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_test_id_fkey', 'questions', 'tests', ['test_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'progresses', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_question_id_fkey', 'answers', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
