"""order_number

Revision ID: 2be42c5c03f2
Revises: 2b5707620d88
Create Date: 2024-08-08 12:49:28.485226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect


# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = '2be42c5c03f2'
down_revision: Union[str, None] = '2b5707620d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)

# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    inspector = sa.inspect(conn)

    if 'order_number' not in [c['name'] for c in inspector.get_columns('tests')]:

        op.add_column('tests', sa.Column('order_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'order_number')
    # ### end Alembic commands ###
