"""mailings

Revision ID: 42a613ed7f5e
Revises: 2be42c5c03f2
Create Date: 2024-09-30 17:48:09.813289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect
from sqlalchemy.dialects import postgresql

from sqlalchemy.engine.reflection import Inspector
conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = '42a613ed7f5e'
down_revision: Union[str, None] = '2be42c5c03f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)

# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if 'mailings' not in tables:
        op.create_table('mailings',
        sa.Column('chat_id', sa.String(length=20), nullable=False),
        sa.Column('message_ids', postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column('was_notified', sa.Boolean(), nullable=False),
        sa.Column('was_stopped', sa.Boolean(), nullable=True),
        sa.Column('was_deleted', sa.Boolean(), nullable=True),
        sa.Column('scheduled_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailings')
    # ### end Alembic commands ###
