"""initial

Revision ID: 543821a6e1e9
Revises: 
Create Date: 2024-06-11 12:00:26.808607

"""
from typing import Sequence, Union

import inspect
import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = '543821a6e1e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if 'users' not in tables:
        op.create_table('users',
                        sa.Column('tg_first_name', sa.String(length=64), nullable=True),
                        sa.Column('tg_last_name', sa.String(length=64), nullable=True),
                        sa.Column('username', sa.String(length=32), nullable=True),
                        sa.Column('registration_date', sa.Date(), nullable=True),
                        sa.Column('admin', sa.Boolean(), nullable=True),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
