"""category_description

Revision ID: a10b6c421b5a
Revises: e921c8f43d69
Create Date: 2024-06-16 04:06:28.290506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect


# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = 'a10b6c421b5a'
down_revision: Union[str, None] = 'e921c8f43d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)

# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
