"""models

Revision ID: b4fcfec6e20d
Revises: 543821a6e1e9
Create Date: 2024-06-11 19:28:39.311193

"""
import inspect
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine.reflection import Inspector

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = 'b4fcfec6e20d'
down_revision: Union[str, None] = '543821a6e1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if 'categories' not in tables:
        op.create_table('categories',
                        sa.Column('name', sa.String(length=100), nullable=False),
                        sa.Column('price', sa.BigInteger(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'payments' not in tables:
        op.create_table('payments',
                        sa.Column('success', sa.Boolean(), nullable=False),
                        sa.Column('category_id', sa.BigInteger(), nullable=False),
                        sa.Column('user_id', sa.BigInteger(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'tests' not in tables:
        op.create_table('tests',
                        sa.Column('name', sa.String(length=100), nullable=False),
                        sa.Column('description', sa.Text(), nullable=True),
                        sa.Column('free', sa.Boolean(), nullable=False),
                        sa.Column('category_id', sa.BigInteger(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'progresses' not in tables:
        op.create_table('progresses',
                        sa.Column('test_id', sa.BigInteger(), nullable=False),
                        sa.Column('user_id', sa.BigInteger(), nullable=False),
                        sa.Column('value', sa.Integer(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
                        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'questions' not in tables:
        op.create_table('questions',
                        sa.Column('test_id', sa.BigInteger(), nullable=False),
                        sa.Column('name', sa.Text(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'results' not in tables:
        op.create_table('results',
                        sa.Column('test_id', sa.BigInteger(), nullable=False),
                        sa.Column('range_from', sa.Integer(), nullable=False),
                        sa.Column('range_to', sa.Integer(), nullable=True),
                        sa.Column('name', sa.Text(), nullable=True),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    if 'answers' not in tables:
        op.create_table('answers',
                        sa.Column('question_id', sa.BigInteger(), nullable=False),
                        sa.Column('name', sa.Text(), nullable=False),
                        sa.Column('value', sa.Integer(), nullable=False),
                        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('updated_at', sa.DateTime(), nullable=False),
                        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                        sa.PrimaryKeyConstraint('id'),
                        sa.UniqueConstraint('id')
                        )
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('users')]
    if 'invited_id' not in columns:
        conn = op.get_bind()

        inspector = sa.inspect(conn)

        if 'invited_id' not in [c['name'] for c in inspector.get_columns('users')]:

            op.add_column('users', sa.Column('invited_id', sa.BigInteger(), nullable=True))
        
    # Check constraints safely
    try:
        conn = op.get_bind()

        res = conn.execute(sa.text("SELECT constraint_name FROM information_schema.table_constraints WHERE table_name = 'users' AND constraint_type = 'UNIQUE'"))

        if not res.fetchall():

            op.create_unique_constraint('uq_users_id', 'users', ['id'])
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'invited_id')
    op.drop_table('answers')
    op.drop_table('results')
    op.drop_table('questions')
    op.drop_table('progresses')
    op.drop_table('tests')
    op.drop_table('payments')
    op.drop_table('categories')
    # ### end Alembic commands ###
