"""pct_banned

Revision ID: dd83b979f58e
Revises: a10b6c421b5a
Create Date: 2024-06-24 22:19:27.261401

"""
from typing import Sequence, Union

import inspect
import sqlalchemy as sa
from alembic import op

# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = 'dd83b979f58e'
down_revision: Union[str, None] = 'a10b6c421b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)


# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('categories', 'description',
    #                 existing_type=sa.TEXT(),
    #                 nullable=True)
    conn = op.get_bind()

    inspector = sa.inspect(conn)

    if 'discount_pct' not in [c['name'] for c in inspector.get_columns('users')]:

        op.add_column('users', sa.Column('discount_pct', sa.Integer(), nullable=True))
    conn = op.get_bind()

    inspector = sa.inspect(conn)

    if 'banned' not in [c['name'] for c in inspector.get_columns('users')]:

        op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    op.drop_column('users', 'discount_pct')
    # op.alter_column('categories', 'description',
    #                 existing_type=sa.TEXT(),
    #                 nullable=False)
    # ### end Alembic commands ###
