"""invited_id

Revision ID: e921c8f43d69
Revises: 0af81bff4115
Create Date: 2024-06-13 04:03:19.443388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, inspect


# from sqlalchemy.engine.reflection import Inspector
# conn = op.get_bind()
# inspector = Inspector.from_engine(conn)
# tables = inspector.get_table_names()

# revision identifiers, used by Alembic.
revision: str = 'e921c8f43d69'
down_revision: Union[str, None] = '0af81bff4115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_context().bind
    insp = inspect(bind)
    columns = insp.get_columns(table_name)
    return any(c["name"] == column_name for c in columns)

# if 'table_name' not in tables:


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invited_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'invited_id',
               existing_type=sa.String(length=64),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
