"""Add premium subscription fields

Revision ID: j4k5l6m7n8p9
Revises: h3c4d5e6f7g8
Create Date: 2026-06-14 02:03:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'j4k5l6m7n8p9'
down_revision: Union[str, None] = 'h3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_opened_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('premium_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('yookassa_payment_method_id', sa.String(length=100), nullable=True))
    
    op.add_column('payments', sa.Column('is_premium_subscription', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('payments', sa.Column('is_recurring', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'is_recurring')
    op.drop_column('payments', 'is_premium_subscription')
    
    op.drop_column('users', 'yookassa_payment_method_id')
    op.drop_column('users', 'premium_until')
    op.drop_column('users', 'first_opened_at')
    # ### end Alembic commands ###
