"""Add has_career_access

Revision ID: m5n6o7p8q9r0
Revises: j4k5l6m7n8p9
Create Date: 2026-06-14 02:18:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'm5n6o7p8q9r0'
down_revision: Union[str, None] = 'j4k5l6m7n8p9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_career_access', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_career_access')
    # ### end Alembic commands ###
